name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main 

env:
  ACR_ADMIN_USERNAME: ${{ secrets.ACR_ADMIN_USERNAME }}
  ACR_ADMIN_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep template
      run: |
        az deployment group create --resource-group myResourceGroup \
          --template-file ./main.bicep \
          --parameters @main.parameters.json \
          acrAdminUsername=${{ secrets.ACR_ADMIN_USERNAME }} \
          acrAdminPassword=${{ secrets.ACR_ADMIN_PASSWORD }}