name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
     
    - name: Deploy to Azure
      run: |
        az deployment group create --resource-group aguadamillas_students_1 --template-file main.bicep --parameters main.parameters.json --parameters acrUsername=${{ secrets.ACR_ADMIN_USERNAME }} acrPassword=${{ secrets.ACR_ADMIN_PASSWORD }}

